# Generated by Django 4.0.6 on 2022-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'One'), ('F', 'Two')], max_length=10)),
            ],
        ),
    ]
